from getrealty import settings, printArray
# import pytest
import os

config = settings.config
hash_global = settings.hash_global

myPath = os.path.dirname(os.path.abspath(__file__))
print('myPath', myPath)

myPA = printArray.MyPrintArray()
myPAarray = myPA.getPrintArray()
myRH = myPA.getReturnHash()


def test_getSecondValueFromHeadingValueCombo():
    assert myPA.getSecondValueFromHeadingValueCombo('wkst_header',
                                                    'NOTES',
                                                    'do_update') == 'No'
    assert myPA.getSecondValueFromHeadingValueCombo('wkst_header',
                                                    'County',
                                                    'do_update') == 'Yes'


def test_storePrintArray():
    pass


def test_getPrintArrayValueByHeading():
    assert myPA.getPrintArrayValueByHeading(
        myPAarray[0], 'wkst_header') == 'NOTES_rnum_sheet'


def test_getPrintArrayHashByValue():
    assert myPA.getPrintArrayHashByValue('wkst_header', 'County') == 1
    assert myPA.getPrintArrayHashByValue('wkst_header', 'BillsF') == 4


def test_getHeadingsFromPrintArray():
    assert myPA.getHeadingsFromPrintArray(
        '1', None) == [
        'NOTES_rnum_sheet', 'County', 'rpg', 'Property_Interest',
        'Files___BillsF', 'Files___HistF', 'Files___DetF', 'Files___DataF',
        'Links___Bills', 'Links___Det', 'Links___Hist', 'Links___Data',
        'Maps___GIS', 'Maps___Map', 'NOTES', 'Subd', 'Prop_Details___Acres',
        'Prop_Details___AssessVal', 'Prop_Details___AssessMinDue',
        'Tax_Due___PctToAss', 'Tax_Due___TotAmtDue', 'DatePulled',
        'TaxDates___OldestDue', 'TaxDates___LastPaid', 'TaxDates___LastYrPaid',
        'Different___Addr', 'Different___Zip', 'Different___State', 'NHS_imp',
        'InstallYr', 'TimesSold___Num', 'TimesSold___Last',
        'Appraised___AppPctOfMax', 'Appraised___AppLastVal',
        'Appraised___AppMaxVal', 'AppraisedMaxReduced___AppMaxAmt',
        'AppraisedMaxReduced___AppMaxYr', 'Assess___AssPctOfMax',
        'Assess___AssLastVal', 'Assess___AssMaxVal',
        'AssessMaxReduced___AssMaxAmt', 'AssessMaxReduced___AssMaxYr',
        'ImpNHS___LastPctOfMax', 'ImpNHS___LastVal', 'ImpNHS___MaxVal',
        'ImpNHSMaxReduced___MaxAmt', 'ImpNHSMaxReduced___MaxYr',
        'ImpHS___ihsPctOfMax', 'ImpHS___ihsLastVal', 'ImpHS___ihsMaxVal',
        'ImpHSMaxReduced___ihsMaxAmt', 'ImpHSMaxReduced___ihsMaxYr',
        'LandHS___lhsPctOfMax', 'LandHS___lhsLastVal', 'LandHS___lhsMaxVal',
        'LandHSMaxReduced___lhsMaxAmt', 'LandHSMaxReduced___lhsMaxYr',
        'LandNHS___lnhsPctOfMax', 'LandNHS___lnhsLastVal',
        'LandNHS___lnhsMaxVal', 'LandNHSMaxReduced___lnhsMaxAmt',
        'LandNHSMaxReduced___lnhsMaxYr', 'DaysLate___Curr', 'DaysLate___Max',
        'PctDiffAddr', 'PropAddr', 'OwnerAddr', 'OwnerName', 'LegalDesc']


def test_CreatePrintHash():
    assert myPA.CreatePrintHash() == {
        'type': {
            'Links___Bills': 'link:Bills',
            'Links___Det': 'link:Det',
            'Links___Hist': 'link:Hist',
            'Links___Data': 'link:Data',
            'Maps___GIS': 'link:GIS',
            'Maps___Map': 'goog'},
        'format': {
            'rpg': 'format1or0',
            'Tax_Due___PctToAss': 'formatpct',
            'Different___Addr': 'format1or0',
            'Different___Zip': 'format1or0',
            'Different___State': 'format1or0',
            'NHS_imp': 'format1or0',
            'Appraised___AppPctOfMax': 'lt_grey',
            'Assess___AssPctOfMax': 'lt_grey',
            'ImpNHS___LastPctOfMax': 'lt_grey',
            'ImpHS___ihsPctOfMax': 'lt_grey',
            'LandHS___lhsPctOfMax': 'lt_grey',
            'LandNHS___lnhsPctOfMax': 'lt_grey',
            'PctDiffAddr': 'format1or0'},
        'cond_format': {},
        'comment': {
            'rpg': 'Does the Rnumber have additional Notes (Rnumber tab)',
            'Subd': 'Subdivision',
            'Prop_Details___AssessMinDue': 'Assessed Minus Tax Amount Due.  Good for Tax Sale List',
            'Tax_Due___PctToAss': 'Percentage of Taxes Due to Assessed Value of the Property',
            'Tax_Due___TotAmtDue': 'Total Amount of Taxes Due at the time the information was pulled',
            'DatePulled': 'Date the Response files were pulled from the server',
            'TaxDates___OldestDue': 'Oldes Taxes Due. Sometimes later year taxes are paid, but older taxes are still due',
            'TaxDates___LastPaid': 'Last Date Taxes were paid.',
            'TaxDates___LastYrPaid': 'Last year taxes were paid.',
            'Different___Addr': 'Owner and Property addresses Differ',
            'Different___Zip': 'Owner and Property zip codes Differ',
            'Different___State': 'Owner and Property states Differ',
            'InstallYr': 'Year Utilites were installed. Value > 7000',
            'TimesSold___Num': 'Number of Times the Property has been sold',
            'TimesSold___Last': 'Last Time the Property was Sold',
            'Appraised___AppPctOfMax': 'Appraised: Percent Current Value / Max Value ever',
            'Appraised___AppLastVal': 'Appraised: Last Value Ever Recoreded',
            'Appraised___AppMaxVal': 'Appraised: Maximum Value Ever Recoreded',
            'AppraisedMaxReduced___AppMaxAmt': 'Appraised: Maximum Reduced Amount from one year to the next',
            'AppraisedMaxReduced___AppMaxYr': 'Appraised: Year Maximum Reduced Amount Occured',
            'Assess___AssPctOfMax': 'Assessed: Percent Current Value / Max Value ever',
            'Assess___AssLastVal': 'Assessed: Last Value Ever Recoreded',
            'Assess___AssMaxVal': 'Assessed: Maximum Value Ever Recoreded',
            'AssessMaxReduced___AssMaxAmt': 'Assessed: Maximum Reduced Amount from one year to the next',
            'AssessMaxReduced___AssMaxYr': 'Assessed: Year Maximum Reduced Amount Occured',
            'ImpNHS___LastPctOfMax': 'Improved Non-Homestead: Percent Current Value / Max Value ever',
            'ImpNHS___LastVal': 'Improved Non-Homestead: Last Value Ever Recoreded',
            'ImpNHS___MaxVal': 'Improved Non-Homestead: Maximum Value Ever Recoreded',
            'ImpNHSMaxReduced___MaxAmt': 'Improved Non-Homestead: Maximum Reduced Amount from one year to the next',
            'ImpNHSMaxReduced___MaxYr': 'Improved Non-Homestead: Year Maximum Reduced Amount Occured',
            'ImpHS___ihsPctOfMax': 'Improved Homestead: Percent Current Value / Max Value ever',
            'ImpHS___ihsLastVal': 'Improved Homestead: Last Value Ever Recoreded',
            'ImpHS___ihsMaxVal': 'Improved Homestead: Maximum Value Ever Recoreded',
            'ImpHSMaxReduced___ihsMaxAmt': 'Improved Homestead: Maximum Reduced Amount from one year to the next',
            'ImpHSMaxReduced___ihsMaxYr': 'Improved Homestead: Year Maximum Reduced Amount Occured',
            'LandHS___lhsPctOfMax': 'Land Homestead: Percent Current Value / Max Value ever',
            'LandHS___lhsLastVal': 'Land Homestead: Last Value Ever Recoreded',
            'LandHS___lhsMaxVal': 'Land Homestead: Maximum Value Ever Recoreded',
            'LandHSMaxReduced___lhsMaxAmt': 'Land Homestead: Maximum Reduced Amount from one year to the next',
            'LandHSMaxReduced___lhsMaxYr': 'Land Homestead: Year Maximum Reduced Amount Occured',
            'LandNHS___lnhsPctOfMax': 'Land Non-Homestead: Percent Current Value / Max Value ever',
            'LandNHS___lnhsLastVal': 'Land Non-Homestead: Last Value Ever Recoreded',
            'LandNHS___lnhsMaxVal': 'Land Non-Homestead: Maximum Value Ever Recoreded',
            'LandNHSMaxReduced___lnhsMaxAmt': 'Land Non-Homestead: Maximum Reduced Amount from one year to the next',
            'LandNHSMaxReduced___lnhsMaxYr': 'Land Non-Homestead: Year Maximum Reduced Amount Occured',
            'DaysLate___Curr': 'Current Number of Days Taxes are Late',
            'DaysLate___Max': 'Maximum Days Late over all years.  Used to determine history of times late',
            'PctDiffAddr': 'Owner and Property addresses Differ'},
        'headers': [
            'rpg',
            'Property_Interest',
            'Links___Bills',
            'Links___Det',
            'Links___Hist',
            'Links___Data',
            'Maps___GIS',
            'Maps___Map',
            'NOTES',
            'Subd',
            'Prop_Details___Acres',
            'Prop_Details___AssessVal',
            'Prop_Details___AssessMinDue',
            'Tax_Due___PctToAss',
            'Tax_Due___TotAmtDue',
            'DatePulled',
            'TaxDates___OldestDue',
            'TaxDates___LastPaid',
            'TaxDates___LastYrPaid',
            'Different___Addr',
            'Different___Zip',
            'Different___State',
            'NHS_imp',
            'InstallYr',
            'TimesSold___Num',
            'TimesSold___Last',
            'Appraised___AppPctOfMax',
            'Appraised___AppLastVal',
            'Appraised___AppMaxVal',
            'AppraisedMaxReduced___AppMaxAmt',
            'AppraisedMaxReduced___AppMaxYr',
            'Assess___AssPctOfMax',
            'Assess___AssLastVal',
            'Assess___AssMaxVal',
            'AssessMaxReduced___AssMaxAmt',
            'AssessMaxReduced___AssMaxYr',
            'ImpNHS___LastPctOfMax',
            'ImpNHS___LastVal',
            'ImpNHS___MaxVal',
            'ImpNHSMaxReduced___MaxAmt',
            'ImpNHSMaxReduced___MaxYr',
            'ImpHS___ihsPctOfMax',
            'ImpHS___ihsLastVal',
            'ImpHS___ihsMaxVal',
            'ImpHSMaxReduced___ihsMaxAmt',
            'ImpHSMaxReduced___ihsMaxYr',
            'LandHS___lhsPctOfMax',
            'LandHS___lhsLastVal',
            'LandHS___lhsMaxVal',
            'LandHSMaxReduced___lhsMaxAmt',
            'LandHSMaxReduced___lhsMaxYr',
            'LandNHS___lnhsPctOfMax',
            'LandNHS___lnhsLastVal',
            'LandNHS___lnhsMaxVal',
            'LandNHSMaxReduced___lnhsMaxAmt',
            'LandNHSMaxReduced___lnhsMaxYr',
            'DaysLate___Curr',
            'DaysLate___Max',
            'PctDiffAddr',
            'PropAddr',
            'OwnerAddr',
            'OwnerName',
            'LegalDesc'],
        'headers_merged': [
            '',
            '',
            'Links',
            'Maps',
            '',
            '',
            'Prop_Details',
            'Tax_Due',
            '',
            'TaxDates',
            'Different',
            '',
            '',
            'TimesSold',
            'Appraised',
            'AppraisedMaxReduced',
            'Assess',
            'AssessMaxReduced',
            'ImpNHS',
            'ImpNHSMaxReduced',
            'ImpHS',
            'ImpHSMaxReduced',
            'LandHS',
            'LandHSMaxReduced',
            'LandNHS',
            'LandNHSMaxReduced',
            'DaysLate',
            '',
            '',
            '',
            '',
            ''],
        'headers_merged_num': {
            'Links': 4,
            'Maps': 2,
            'Prop_Details': 3,
            'Tax_Due': 2,
            'TaxDates': 3,
            'Different': 3,
            'TimesSold': 2,
            'Appraised': 3,
            'AppraisedMaxReduced': 2,
            'Assess': 3,
            'AssessMaxReduced': 2,
            'ImpNHS': 3,
            'ImpNHSMaxReduced': 2,
            'ImpHS': 3,
            'ImpHSMaxReduced': 2,
            'LandHS': 3,
            'LandHSMaxReduced': 2,
            'LandNHS': 3,
            'LandNHSMaxReduced': 2,
            'DaysLate': 2}}
